name: deepdfa
channels:
  - defaults
dependencies:
  - python=3.10
  - cudatoolkit=11.8
  - pip
  - pip:
    - -f https://data.dgl.ai/wheels/cu117/repo.html
    - dgl<1.1.3
    - numpy
    - pandas
    - tqdm
    - pytorch-lightning==1.7.0 # https://lightning.ai/docs/pytorch/latest/versioning.html#pytorch-support
    - --extra-index-url https://download.pytorch.org/whl/cu116
    - torch>=1.9,<=1.12
    - torchmetrics<0.10.0
    - torchsampler
    - nni
    - silence-tensorflow
    - tensorflow
    - scipy
    - captum
    - deepspeed
    - scikit-learn
    - tokenizers
    - transformers
    - tree-sitter
    - unidiff
    - jsonlines
    - networkx
    - pexpect
    - jsonargparse[signatures]
    - fastparquet
    - gdown